from decimal import Decimal

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string
from django.forms.utils import ErrorDict, ErrorList
from django.core.exceptions import ValidationError

from .models import ClientProfile, ClientRequest, ManagerProfile, Payment, PaymentProof, Project, RequestAttachment


class AutoGeneratedPasswordMixin:
    def __init__(self, *args, **kwargs):
        data = kwargs.get('data')
        if data is None and args:
            data = args[0]

        if data is not None:
            data = data.copy()
            name_value = data.get('name', '')
            name_value = str(name_value).strip()
            pwd1 = data.get('password1', '')
            pwd2 = data.get('password2', '')
            if name_value and (not pwd1 or not pwd2):
                mobile = data.get('mobile_number', '')
                generated = self._generate_autogenerated_password(name_value, mobile)
                data['password1'] = generated
                data['password2'] = generated
                self._auto_generated_password = True

                if 'data' in kwargs:
                    kwargs['data'] = data
                else:
                    args = (data,) + args[1:]

        super().__init__(*args, **kwargs)

    @staticmethod
    def _generate_autogenerated_password(name_value, mobile):
        normalized_name = ''.join(ch for ch in str(name_value).strip() if ch.isalnum())
        if not normalized_name:
            normalized_name = get_random_string(4)
        digits = ''.join(ch for ch in (mobile or '') if ch.isdigit())
        last4 = digits[-4:] if digits else ''
        base = f"{normalized_name}@{last4}" if last4 else f"{normalized_name}@{get_random_string(4)}"
        symbol = get_random_string(1, allowed_chars='!@#$%&*')
        suffix = get_random_string(4)
        pwd = f"{base}{symbol}{suffix}"
        if len(pwd) < 10:
            pwd += get_random_string(10 - len(pwd))
        return pwd

    def _remove_password_similarity_error(self):
        if not getattr(self, '_auto_generated_password', False):
            return
        if not hasattr(self, '_errors') or self._errors is None:
            return
        if 'password2' not in self._errors:
            return

        kept = []
        for err in self._errors.get('password2', []):
            code = getattr(err, 'code', None)
            if code == 'password_too_similar':
                continue
            kept.append(err)

        if kept:
            messages = []
            for e in kept:
                if hasattr(e, 'message'):
                    messages.append(str(e.message))
                else:
                    messages.append(str(e))
            self._errors['password2'] = ErrorList(messages)
        else:
            del self._errors['password2']

    def _post_clean(self):
        super()._post_clean()
        self._remove_password_similarity_error()


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))


class ClientSignupForm(AutoGeneratedPasswordMixin, UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=150, required=True)
    last_name = forms.CharField(max_length=150, required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data.get('last_name', '')
        user.is_staff = False
        if commit:
            user.save()
        return user



class ClientEditForm(forms.ModelForm):
    name = forms.CharField(max_length=150, required=True)
    mobile_number = forms.CharField(max_length=20, required=True)

    class Meta:
        model = User
        fields = ('name', 'username', 'email', 'mobile_number')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields['name'].initial = self.instance.get_full_name() or self.instance.first_name
            self.fields['mobile_number'].initial = getattr(getattr(self.instance, 'client_profile', None), 'mobile_number', '')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['name']
        user.last_name = ''
        if commit:
            user.save()
            ClientProfile.objects.update_or_create(
                user=user,
                defaults={'mobile_number': self.cleaned_data['mobile_number']},
            )
        return user


class AdminClientCreateForm(AutoGeneratedPasswordMixin, UserCreationForm):
    email = forms.EmailField(required=True)
    name = forms.CharField(max_length=150, required=True)
    mobile_number = forms.CharField(max_length=20, required=True)
    PROJECT_SELECT = ''
    PROJECT_CREATE = '__create_new__'

    project_action = forms.ChoiceField(
        choices=[(PROJECT_SELECT, 'Select'), (PROJECT_CREATE, 'Create New Project')],
        required=False,
        label='Project',
    )

    projects = forms.ModelMultipleChoiceField(
        queryset=Project.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple(),
        label='Projects',
    )

    class Meta:
        model = User
        fields = (
            'name',
            'username',
            'email',
            'mobile_number',
            'project_action',
            'projects',
            'password1',
            'password2',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        project_choices = [(self.PROJECT_SELECT, 'Select'), (self.PROJECT_CREATE, 'Create New Project')]
        project_choices.extend((str(project.pk), project.name) for project in Project.objects.all())
        self.fields['project_action'].choices = project_choices
        self.fields['projects'].queryset = Project.objects.all()

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['name']
        user.last_name = ''
        user.is_staff = False
        user.is_superuser = False
        if commit:
            user.save()
            ClientProfile.objects.update_or_create(
                user=user,
                defaults={'mobile_number': self.cleaned_data['mobile_number']},
            )
            project = None
            project_action = self.cleaned_data.get('project_action')
            if project_action == self.PROJECT_CREATE:
                project = Project.objects.create(
                    name=f"{self.cleaned_data['name']}'s Project",
                    description='Created from Add Client.',
                    status=Project.STATUS_ACTIVE,
                )
                project.clients.add(user)
            # add any explicitly selected projects
            for project in self.cleaned_data.get('projects', []):
                project.clients.add(user)
        return user




class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'description', 'status', 'clients', 'managers')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
            'clients': forms.CheckboxSelectMultiple(),
            'managers': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = User.objects.filter(is_staff=False, is_superuser=False).order_by('first_name', 'username')
        self.fields['managers'].queryset = User.objects.filter(is_staff=True, is_superuser=False).order_by('first_name', 'username')


class ManagerCreateForm(AutoGeneratedPasswordMixin, UserCreationForm):
    name = forms.CharField(max_length=150, required=True)
    email = forms.EmailField(required=True)
    mobile_number = forms.CharField(max_length=20, required=False)
    ROLE_SELECT = ''
    role = forms.ChoiceField(
        required=False,
        label='Role',
        choices=[
            (ROLE_SELECT, 'Select'),
            (ManagerProfile.ROLE_DEVELOPER, 'Developer'),
            (ManagerProfile.ROLE_PM, 'Project Manager'),
            (ManagerProfile.ROLE_TESTER, 'Tester'),
        ],
    )
    projects = forms.ModelMultipleChoiceField(
        queryset=Project.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple(),
    )

    class Meta:
        model = User
        fields = ('name', 'username', 'email', 'mobile_number', 'role', 'projects', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['name']
        user.email = self.cleaned_data['email']
        user.is_staff = True
        user.is_superuser = False
        if commit:
            user.save()
            ManagerProfile.objects.update_or_create(
                user=user,
                defaults={
                    'mobile_number': self.cleaned_data.get('mobile_number', ''),
                    'role': self.cleaned_data.get('role', ''),
                },
            )
            for project in self.cleaned_data.get('projects', []):
                project.managers.add(user)
        return user




class ManagerEditForm(forms.ModelForm):
    name = forms.CharField(max_length=150, required=True)
    mobile_number = forms.CharField(max_length=20, required=False)
    projects = forms.ModelMultipleChoiceField(
        queryset=Project.objects.all(),
        required=False,
        widget=forms.SelectMultiple(attrs={'class': 'searchable-select', 'size': 6}),
    )
    ROLE_SELECT = ''
    role = forms.ChoiceField(
        required=False,
        label='Role',
        choices=[(ROLE_SELECT, 'Select')] + ManagerProfile.ROLE_CHOICES,
    )

    class Meta:
        model = User
        fields = ('name', 'username', 'email', 'mobile_number', 'projects')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields['name'].initial = self.instance.get_full_name() or self.instance.username
            self.fields['mobile_number'].initial = getattr(getattr(self.instance, 'manager_profile', None), 'mobile_number', '')
            self.fields['projects'].initial = self.instance.managed_projects.all()
            self.fields['role'].initial = getattr(getattr(self.instance, 'manager_profile', None), 'role', '')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['name']
        user.last_name = ''
        user.is_staff = True
        user.is_superuser = False
        if commit:
            user.save()
            ManagerProfile.objects.update_or_create(
                user=user,
                defaults={
                    'mobile_number': self.cleaned_data.get('mobile_number', ''),
                    'role': self.cleaned_data.get('role', ''),
                },
            )
            user.managed_projects.clear()
            for project in self.cleaned_data.get('projects', []):
                project.managers.add(user)
        return user


class ClientRequestForm(forms.ModelForm):
    class Meta:
        model = ClientRequest
        fields = ('project', 'title', 'service_type', 'description')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields['project'].queryset = user.projects.all()


class AdminRequestUpdateForm(forms.ModelForm):
    upload_file = forms.FileField(required=False, label='Upload Files')

    class Meta:
        model = ClientRequest
        fields = ('status', 'admin_response')
        widgets = {
            'admin_response': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Write a clear update for the client...'}),
        }


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ('client', 'project', 'request', 'amount', 'status', 'date', 'notes')
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'notes': forms.Textarea(attrs={'rows': 3}),
        }


class PaymentRequestForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ('client', 'project', 'request', 'amount', 'date', 'notes')
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'notes': forms.Textarea(attrs={'rows': 3}),
        }

    def save(self, commit=True):
        payment = super().save(commit=False)
        payment.status = Payment.STATUS_UNPAID
        if commit:
            payment.save()
        return payment


class PaymentReceiveForm(forms.Form):
    payment = forms.ModelChoiceField(queryset=Payment.objects.select_related('client', 'project').all())
    approved_proofs = forms.ModelMultipleChoiceField(
        queryset=PaymentProof.objects.none(),
        required=False,
        widget=forms.SelectMultiple(attrs={'class': 'searchable-select', 'size': 5}),
        label='Approved Payment Proof IDs',
    )
    amount = forms.DecimalField(max_digits=10, decimal_places=2, min_value=Decimal('0.01'))
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    notes = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['approved_proofs'].queryset = PaymentProof.objects.filter(status=PaymentProof.STATUS_REVIEWED).select_related('payment', 'client')


class ClientPaymentProofForm(forms.ModelForm):
    class Meta:
        model = PaymentProof
        fields = ('payment', 'amount', 'proof_image', 'note')
        widgets = {
            'note': forms.Textarea(attrs={'rows': 3}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields['payment'].queryset = user.payments.exclude(status=Payment.STATUS_PAID).select_related('project', 'request')
